CREATE TABLE solicitacoes_orcamentos (
    solicitante VARCHAR(255) NOT NULL,
    nome_solicitante VARCHAR(255) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    canal_contato VARCHAR(50) NOT NULL,
    codigo_solicitacao INT AUTO_INCREMENT PRIMARY KEY,
    data_solicitacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    protocolo VARCHAR(20) NOT NULL UNIQUE,
    origem_orcamento VARCHAR(255) NOT NULL,
    tipo_orcamento VARCHAR(255) NOT NULL,
    convenio VARCHAR(255) NOT NULL,
    observacoes_adicionais TEXT,
    nome_paciente VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    comorbidades BOOLEAN DEFAULT FALSE,
    descricao_comorbidades TEXT,
    resumo_procedimento TEXT,
    detalhes_procedimento TEXT,
    tempo_cirurgia TIME,
    data_provavel DATE,
    diarias_enfermaria INT DEFAULT 0,
    diarias_apartamento INT DEFAULT 0,
    diarias_uti INT DEFAULT 0,
    anestesia_raqui BOOLEAN DEFAULT FALSE,
    anestesia_sma BOOLEAN DEFAULT FALSE,
    anestesia_peridural BOOLEAN DEFAULT FALSE,
    anestesia_sedacao BOOLEAN DEFAULT FALSE,
    anestesia_externo BOOLEAN DEFAULT FALSE,
    anestesia_bloqueio BOOLEAN DEFAULT FALSE,
    anestesia_local BOOLEAN DEFAULT FALSE,
    anestesia_outros VARCHAR(255) DEFAULT NULL
);


DELIMITER //
CREATE TRIGGER before_insert_solicitacoes_orcamentos
BEFORE INSERT ON solicitacoes_orcamentos
FOR EACH ROW
BEGIN
    SET NEW.protocolo = CONCAT('PRT', LPAD(FLOOR(RAND() * 1000000), 6, '0'));
END //
DELIMITER ;

CREATE TABLE tabela_de_precos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome_tabela VARCHAR(255) NOT NULL,
    procedimento1 DECIMAL(10,2) DEFAULT NULL,
    procedimento2 DECIMAL(10,2) DEFAULT NULL,
    procedimento3 DECIMAL(10,2) DEFAULT NULL,
    procedimento4 DECIMAL(10,2) DEFAULT NULL,
    procedimento5 DECIMAL(10,2) DEFAULT NULL,
    procedimento6 DECIMAL(10,2) DEFAULT NULL,
    procedimento7 DECIMAL(10,2) DEFAULT NULL,
    procedimento8 DECIMAL(10,2) DEFAULT NULL,
    procedimento9 DECIMAL(10,2) DEFAULT NULL,
    procedimento10 DECIMAL(10,2) DEFAULT NULL,
    procedimento11 DECIMAL(10,2) DEFAULT NULL,
    procedimento12 DECIMAL(10,2) DEFAULT NULL,
    procedimento13 DECIMAL(10,2) DEFAULT NULL,
    procedimento14 DECIMAL(10,2) DEFAULT NULL,
    procedimento15 DECIMAL(10,2) DEFAULT NULL
);

CREATE TABLE orcamentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cod_solicitacao INT NOT NULL,
    id_user_visualizar JSON NOT NULL,
    id_user_editar JSON NOT NULL,
    id_tabela_precos INT NOT NULL,
    valor_procedimento1 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento2 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento3 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento4 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento5 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento6 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento7 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento8 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento9 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento10 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento11 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento12 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento13 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento14 DECIMAL(10, 2) DEFAULT NULL,
    valor_procedimento15 DECIMAL(10, 2) DEFAULT NULL,
    solicitante VARCHAR(255) NOT NULL,
    nome_solicitante VARCHAR(255) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    canal_contato VARCHAR(50) NOT NULL,
    protocolo VARCHAR(20) NOT NULL UNIQUE,
    origem_orcamento VARCHAR(255) NOT NULL,
    tipo_orcamento VARCHAR(255) NOT NULL,
    convenio VARCHAR(255) NOT NULL,
    observacoes_adicionais TEXT,
    nome_paciente VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    comorbidades BOOLEAN DEFAULT FALSE,
    descricao_comorbidades TEXT,
    resumo_procedimento TEXT,
    detalhes_procedimento TEXT,
    tempo_cirurgia TIME,
    data_provavel DATE,
    diarias_enfermaria INT DEFAULT 0,
    diarias_apartamento INT DEFAULT 0,
    diarias_uti INT DEFAULT 0,
    anestesia_raqui BOOLEAN DEFAULT FALSE,
    anestesia_sma BOOLEAN DEFAULT FALSE,
    anestesia_peridural BOOLEAN DEFAULT FALSE,
    anestesia_sedacao BOOLEAN DEFAULT FALSE,
    anestesia_externo BOOLEAN DEFAULT FALSE,
    anestesia_bloqueio BOOLEAN DEFAULT FALSE,
    anestesia_local BOOLEAN DEFAULT FALSE,
    anestesia_outros VARCHAR(255) DEFAULT NULL
    status ENUM('Pendente', 'Em andamento', 'Concluído', 'Cancelado') NOT NULL DEFAULT 'Pendente',
    FOREIGN KEY (cod_solicitacao) REFERENCES solicitacoes_orcamentos(id),
    FOREIGN KEY (id_tabela_precos) REFERENCES tabela_de_precos(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
